package ORM;
// Generated 08-may-2020 11:30:47 by Hibernate Tools 4.3.1



/**
 * Marcas generated by hbm2java
 */
public class Marcas  implements java.io.Serializable {


     private Integer idMarca;
     private Villanos villanos;
     private String nomMarca;
     private int anioCreacion;
     private Boolean pelicula;

    public Marcas() {
    }

	
    public Marcas(Villanos villanos, String nomMarca, int anioCreacion) {
        this.villanos = villanos;
        this.nomMarca = nomMarca;
        this.anioCreacion = anioCreacion;
    }
    public Marcas(Villanos villanos, String nomMarca, int anioCreacion, Boolean pelicula) {
       this.villanos = villanos;
       this.nomMarca = nomMarca;
       this.anioCreacion = anioCreacion;
       this.pelicula = pelicula;
    }
   
    public Integer getIdMarca() {
        return this.idMarca;
    }
    
    public void setIdMarca(Integer idMarca) {
        this.idMarca = idMarca;
    }
    public Villanos getVillanos() {
        return this.villanos;
    }
    
    public void setVillanos(Villanos villanos) {
        this.villanos = villanos;
    }
    public String getNomMarca() {
        return this.nomMarca;
    }
    
    public void setNomMarca(String nomMarca) {
        this.nomMarca = nomMarca;
    }
    public int getAnioCreacion() {
        return this.anioCreacion;
    }
    
    public void setAnioCreacion(int anioCreacion) {
        this.anioCreacion = anioCreacion;
    }
    public Boolean getPelicula() {
        return this.pelicula;
    }
    
    public void setPelicula(Boolean pelicula) {
        this.pelicula = pelicula;
    }




}


