package ORM;
// Generated 08-may-2020 11:30:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Superheroes generated by hbm2java
 */
public class Superheroes  implements java.io.Serializable {


     private Integer idSuperheroe;
     private String nomSuperheroe;
     private String habilidad;
     private Boolean capa;
     private char genero;
     private Set villanoses = new HashSet(0);
     private Set superpodereses = new HashSet(0);

    public Superheroes() {
    }

    public Superheroes(String nomSuperheroe) {
        this.nomSuperheroe = nomSuperheroe;
    }

    
	
    public Superheroes(String nomSuperheroe, String habilidad, char genero) {
        this.nomSuperheroe = nomSuperheroe;
        this.habilidad = habilidad;
        this.genero = genero;
    }
    public Superheroes(String nomSuperheroe, String habilidad, Boolean capa, char genero, Set villanoses, Set superpodereses) {
       this.nomSuperheroe = nomSuperheroe;
       this.habilidad = habilidad;
       this.capa = capa;
       this.genero = genero;
       this.villanoses = villanoses;
       this.superpodereses = superpodereses;
    }
   
    public Integer getIdSuperheroe() {
        return this.idSuperheroe;
    }
    
    public void setIdSuperheroe(Integer idSuperheroe) {
        this.idSuperheroe = idSuperheroe;
    }
    public String getNomSuperheroe() {
        return this.nomSuperheroe;
    }
    
    public void setNomSuperheroe(String nomSuperheroe) {
        this.nomSuperheroe = nomSuperheroe;
    }
    public String getHabilidad() {
        return this.habilidad;
    }
    
    public void setHabilidad(String habilidad) {
        this.habilidad = habilidad;
    }
    public Boolean getCapa() {
        return this.capa;
    }
    
    public void setCapa(Boolean capa) {
        this.capa = capa;
    }
    public char getGenero() {
        return this.genero;
    }
    
    public void setGenero(char genero) {
        this.genero = genero;
    }
    public Set getVillanoses() {
        return this.villanoses;
    }
    
    public void setVillanoses(Set villanoses) {
        this.villanoses = villanoses;
    }
    public Set getSuperpodereses() {
        return this.superpodereses;
    }
    
    public void setSuperpodereses(Set superpodereses) {
        this.superpodereses = superpodereses;
    }




}


