package ORM;
// Generated 08-may-2020 11:30:47 by Hibernate Tools 4.3.1



/**
 * Superpoderes generated by hbm2java
 */
public class Superpoderes  implements java.io.Serializable {


     private Integer idSuperpoder;
     private Superheroes superheroes;
     private String nomPoder;
     private int danio;
     private int potencia;

    public Superpoderes() {
    }

    public Superpoderes(Superheroes superheroes, String nomPoder, int danio, int potencia) {
       this.superheroes = superheroes;
       this.nomPoder = nomPoder;
       this.danio = danio;
       this.potencia = potencia;
    }
   
    public Integer getIdSuperpoder() {
        return this.idSuperpoder;
    }
    
    public void setIdSuperpoder(Integer idSuperpoder) {
        this.idSuperpoder = idSuperpoder;
    }
    public Superheroes getSuperheroes() {
        return this.superheroes;
    }
    
    public void setSuperheroes(Superheroes superheroes) {
        this.superheroes = superheroes;
    }
    public String getNomPoder() {
        return this.nomPoder;
    }
    
    public void setNomPoder(String nomPoder) {
        this.nomPoder = nomPoder;
    }
    public int getDanio() {
        return this.danio;
    }
    
    public void setDanio(int danio) {
        this.danio = danio;
    }
    public int getPotencia() {
        return this.potencia;
    }
    
    public void setPotencia(int potencia) {
        this.potencia = potencia;
    }




}


